<?php
class error
{
	const USERNAME_EXISTS = 1;
	const PASS_CONNT_EXISTS = 2;
	const USERNAME_CONNT_EXISTS=3;
	const REGIST_FAIL=4;
	const LOGIN_FAIL=5;
	
	const TITLE_CONNT_EXISTS=6;
	const CONTENT_CONNT_EXISTS=7;
	const ARTICLE_FAIL=8;
	
	const ARTICLE_ID_NULL=9;
	const ARTICLE_NOT_FOUND=10;
	
	const HAVE_NO_PRI=11;
	const ARTICLE_UPDATE_FAIL=12;
	const ARTICLE_DEL_FAIL=13;
	const ARTICLE_NO_HAVE=14;
	const ARTICLE_HAVE_FAIL=15;
	const ARTICLE_PAGE_MANY=16;
}